server:
  port: 8084
spring:
  application:
    name: cash
feign:
  accounts: http://localhost:8089/accounts
  blocker: http://localhost:8089/blocker
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/