server:
  port: 8089
spring:
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: accounts
              uri: http://localhost:8081
              predicates:
                - Path=/accounts/**
          default-filters:
            - StripPrefix=1