server:
  port: 8089
spring:
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: accounts
              uri: lb://accounts
              predicates:
                - Path=/accounts/**
            - id: blocker
              uri: lb://blocker
              predicates:
                - Path=/blocker/**
            - id: cash
              uri: lb://cash
              predicates:
                - Path=/cash/**
            - id: exchange
              uri: lb://exchange
              predicates:
                - Path=/exchange/**
            - id: exchange-generator
              uri: lb://exchange-generator
              predicates:
                - Path=/exchange-generator/**
            - id: notifications
              uri: lb://notifications
              predicates:
                - Path=/notifications/**
            - id: transfer
              uri: lb://transfer
              predicates:
                - Path=/transfer/**
          default-filters:
            - StripPrefix=1
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/